spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 5721655f816aeb809835b40b8f42d917
          google:
            client-id: 516958134574-t26vta8u0dmvvkcgb8k8rpvdmacfq5t6.apps.googleusercontent.com
            client-secret: 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